name:                webmonad
version:             0.1.0.0
homepage:            https://github.com/noxecane/webmonad
license:             AllRightsReserved
author:              Arewa Olakunle
maintainer:          arewa.olakunle@gmail.com
copyright:           Arewa Olakunle
category:            web

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Widentities
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fhide-source-paths

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - exceptions
  - mtl
  - opaleye
  - profunctors
  - product-profunctors
  - postgresql-simple
  - random
  - split
  - template-haskell
  - text
  - time
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Control.Monad.X.Web
    - Data.X.AlaCarte
    - Data.X.Parser
    - Data.X.Time
    - Opaleye.X
    - Opaleye.X.Alias
    - Opaleye.X.TH
    - Prelude.X